/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.ActionField
import SigniFlow.Connect.models.ProxyAllowedField
import SigniFlow.Connect.models.TokenField

import com.squareup.moshi.Json

/**
 * #### Add a step to the Workflow request.
 * @param actionField 
 * @param cellField Mobile number of participant
 * @param docIDField Document ID field.
 * @param emailField Participant email address.
 * @param firstNameField Participant firstname.
 * @param languageCodeField Participant 2 Digit ISO Language Code `en = English es = Spanish fr = French ect`
 * @param lastNameField Participant last name.
 * @param proxyAllowedField 
 * @param tokenField 
 */

data class AddWorkflowStepV2Request (
    @Json(name = "ActionField")
    val actionField: ActionField,
    /* Mobile number of participant */
    @Json(name = "CellField")
    val cellField: kotlin.String,
    /* Document ID field. */
    @Json(name = "DocIDField")
    val docIDField: kotlin.String,
    /* Participant email address. */
    @Json(name = "EmailField")
    val emailField: kotlin.String,
    /* Participant firstname. */
    @Json(name = "FirstNameField")
    val firstNameField: kotlin.String,
    /* Participant 2 Digit ISO Language Code `en = English es = Spanish fr = French ect` */
    @Json(name = "LanguageCodeField")
    val languageCodeField: kotlin.String,
    /* Participant last name. */
    @Json(name = "LastNameField")
    val lastNameField: kotlin.String,
    @Json(name = "ProxyAllowedField")
    val proxyAllowedField: ProxyAllowedField,
    @Json(name = "TokenField")
    val tokenField: TokenField
)

