/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.ActionField

import com.squareup.moshi.Json

/**
 * 
 * @param actionField 
 * @param emailField Participant email address field.
 * @param flowIDField Document Flow ID field.
 */

data class AddWokflowStepV2ResponseFlowStepsField (
    @Json(name = "ActionField")
    val actionField: ActionField,
    /* Participant email address field. */
    @Json(name = "EmailField")
    val emailField: kotlin.String,
    /* Document Flow ID field. */
    @Json(name = "FlowIDField")
    val flowIDField: java.math.BigDecimal
)

