/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.FieldType

import com.squareup.moshi.Json

/**
 * #### The response retuenrd when fields are added to a document using a FlowID.
 * @param docIDField Document ID.
 * @param fieldTypeField 
 * @param heightField The height of the field.
 * @param pageNumberField Field page number.
 * @param prepperFieldIDField Document prepper field ID.
 * @param resultField Displays the result of the call.
 * @param userIDField SigniFlow User ID
 * @param widthField The width of the field.
 * @param xcoordinateField X-coordinates of the field.
 * @param ycoordinateField Y-coordinates of the field.
 */

data class DocPrepperAddFieldsFlowIDResponse (
    /* Document ID. */
    @Json(name = "DocIDField")
    val docIDField: java.math.BigDecimal,
    @Json(name = "FieldTypeField")
    val fieldTypeField: FieldType,
    /* The height of the field. */
    @Json(name = "HeightField")
    val heightField: kotlin.String,
    /* Field page number. */
    @Json(name = "PageNumberField")
    val pageNumberField: java.math.BigDecimal,
    /* Document prepper field ID. */
    @Json(name = "PrepperFieldIDField")
    val prepperFieldIDField: java.math.BigDecimal,
    /* Displays the result of the call. */
    @Json(name = "ResultField")
    val resultField: kotlin.String,
    /* SigniFlow User ID */
    @Json(name = "UserIDField")
    val userIDField: java.math.BigDecimal,
    /* The width of the field. */
    @Json(name = "WidthField")
    val widthField: kotlin.String,
    /* X-coordinates of the field. */
    @Json(name = "XCoordinateField")
    val xcoordinateField: kotlin.String,
    /* Y-coordinates of the field. */
    @Json(name = "YCoordinateField")
    val ycoordinateField: kotlin.String
)

