/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.DocPrepperAddAdvancedFieldsRequestFieldInfoListField
import SigniFlow.Connect.models.TokenField

import com.squareup.moshi.Json

/**
 * #### A request sent to add advanced fields to a document.
 * @param fieldInfoListField Field information list field.
 * @param tokenField 
 */

data class DocPrepperAddAdvancedFieldsRequest (
    /* Field information list field. */
    @Json(name = "FieldInfoListField")
    val fieldInfoListField: kotlin.collections.List<DocPrepperAddAdvancedFieldsRequestFieldInfoListField>,
    @Json(name = "TokenField")
    val tokenField: TokenField
)

