/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField

import com.squareup.moshi.Json

/**
 * #### This is the response when adding advanced fields to a document.
 * @param advancedFieldResponseListField 
 * @param resultField Displays the result of the call.
 */

data class DocPrepperAddAdvancedFieldsResponse (
    @Json(name = "AdvancedFieldResponseListField")
    val advancedFieldResponseListField: kotlin.collections.List<DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField>,
    /* Displays the result of the call. */
    @Json(name = "ResultField")
    val resultField: kotlin.String
)

