/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.AdvancedFieldType
import SigniFlow.Connect.models.DocPrepperAddAdvancedFieldsRequestFieldOptionsListField

import com.squareup.moshi.Json

/**
 * 
 * @param advancedFieldTypeField 
 * @param docIDField Document ID field.
 * @param flowIDField Document Flow ID field.
 * @param fontFamilyField Font family of the text in the field
 * @param fontSizeField Font size of the text in the field
 * @param heightField Field height
 * @param widthField Field Width
 * @param linkToField 
 * @param nameField 
 * @param pageNumberField Field page number.
 * @param searchableField 
 * @param userEmailField User email address.
 * @param valueField 
 * @param xcoordinateField X-coordinates of field on the page
 * @param ycoordinateField Y-coordinates of field on the page
 * @param fieldOptionsListField 
 */

data class DocPrepperAddAdvancedFieldsRequestFieldInfoListField (
    @Json(name = "AdvancedFieldTypeField")
    val advancedFieldTypeField: AdvancedFieldType,
    /* Document ID field. */
    @Json(name = "DocIDField")
    val docIDField: java.math.BigDecimal,
    /* Document Flow ID field. */
    @Json(name = "FlowIDField")
    val flowIDField: java.math.BigDecimal,
    /* Font family of the text in the field */
    @Json(name = "FontFamilyField")
    val fontFamilyField: kotlin.String,
    /* Font size of the text in the field */
    @Json(name = "FontSizeField")
    val fontSizeField: java.math.BigDecimal,
    /* Field height */
    @Json(name = "HeightField")
    val heightField: kotlin.String,
    /* Field Width */
    @Json(name = "WidthField")
    val widthField: kotlin.String,
    @Json(name = "LinkToField")
    val linkToField: kotlin.String,
    @Json(name = "NameField")
    val nameField: kotlin.String,
    /* Field page number. */
    @Json(name = "PageNumberField")
    val pageNumberField: java.math.BigDecimal,
    @Json(name = "SearchableField")
    val searchableField: kotlin.Boolean,
    /* User email address. */
    @Json(name = "UserEmailField")
    val userEmailField: kotlin.String,
    @Json(name = "ValueField")
    val valueField: kotlin.String,
    /* X-coordinates of field on the page */
    @Json(name = "XCoordinateField")
    val xcoordinateField: kotlin.String,
    /* Y-coordinates of field on the page */
    @Json(name = "YCoordinateField")
    val ycoordinateField: kotlin.String,
    @Json(name = "FieldOptionsListField")
    val fieldOptionsListField: kotlin.collections.List<DocPrepperAddAdvancedFieldsRequestFieldOptionsListField>? = null
)

