/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.FieldType
import SigniFlow.Connect.models.TokenField

import com.squareup.moshi.Json

/**
 * #### The request sent when fields are added to a document using a FlowID.
 * @param docFieldTypeField 
 * @param docIDField Document ID.
 * @param flowIDField Document Flow ID.
 * @param heightField Field height.
 * @param widthField Field width.
 * @param isInvisibleField Is the field invisible.
 * @param linkToField Document link.
 * @param pageNumberField Field page number.
 * @param nameField Field name field.
 * @param userEmailField User email address field.
 * @param xcoordinateField Document field x-coordinates.
 * @param ycoordinateField Document field y-coordinates.
 * @param tokenField 
 */

data class DocPrepperAddFieldsFlowIDRequest (
    @Json(name = "DocFieldTypeField")
    val docFieldTypeField: FieldType,
    /* Document ID. */
    @Json(name = "DocIDField")
    val docIDField: java.math.BigDecimal,
    /* Document Flow ID. */
    @Json(name = "FlowIDField")
    val flowIDField: java.math.BigDecimal,
    /* Field height. */
    @Json(name = "HeightField")
    val heightField: kotlin.String,
    /* Field width. */
    @Json(name = "WidthField")
    val widthField: kotlin.String,
    /* Is the field invisible. */
    @Json(name = "IsInvisibleField")
    val isInvisibleField: kotlin.Boolean,
    /* Document link. */
    @Json(name = "LinkToField")
    val linkToField: kotlin.String,
    /* Field page number. */
    @Json(name = "PageNumberField")
    val pageNumberField: java.math.BigDecimal,
    /* Field name field. */
    @Json(name = "NameField")
    val nameField: kotlin.String,
    /* User email address field. */
    @Json(name = "UserEmailField")
    val userEmailField: kotlin.String,
    /* Document field x-coordinates. */
    @Json(name = "XCoordinateField")
    val xcoordinateField: kotlin.String,
    /* Document field y-coordinates. */
    @Json(name = "YCoordinateField")
    val ycoordinateField: kotlin.String,
    @Json(name = "TokenField")
    val tokenField: TokenField
)

