/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * #### The response returned when a user wants to download a portfolio.
 * @param portfolioDataField Portfolio data field.
 * @param portfolioIDField Portfolio ID.
 * @param portfolioNameField Portfolio name.
 * @param resultField Displays the result of the call.
 */

data class DownloadPortfolioResponse (
    /* Portfolio data field. */
    @Json(name = "PortfolioDataField")
    val portfolioDataField: kotlin.String,
    /* Portfolio ID. */
    @Json(name = "PortfolioIDField")
    val portfolioIDField: java.math.BigDecimal,
    /* Portfolio name. */
    @Json(name = "PortfolioNameField")
    val portfolioNameField: kotlin.String,
    /* Displays the result of the call. */
    @Json(name = "ResultField")
    val resultField: kotlin.String
)

