/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
* #### Document Prepper Field Types  ` 0  = Signature 1  = NameText 2  = DateText 3  = EmailAddressText 4  = ContactNumberText 5  = PlainText 6  = PlainTextOptional 7  = FaceToface 8  = Initial 9  = CheckBox 10 = F2FInitial 11 = AddressText 12 = CompanyNameText 13 = OptionalCurrencyText 14 = MandatoryCurrencyText 15 = ReadOnlyText 16 = NumericFieldOpt 17 = NumericFieldMand 18 = EmailInputOptional 19 = EmailInput `
* Values: Signature,NameText,DateText,EmailAddressText,ContactNumberText,PlainText,PlainTextOptional,FaceToface,Initial,CheckBox,F2FInitial,AddressText,CompanyNameText,OptionalCurrencyText,ReadOnlyText,NumericFieldOpt,NumericFieldMand,EmailInputOptional,EmailInput,_19
*/

enum class FieldType(val value: kotlin.Int) {


    @Json(name = "0")
    Signature(0),

    @Json(name = "1")
    NameText(1),

    @Json(name = "2")
    DateText(2),

    @Json(name = "3")
    EmailAddressText(3),

    @Json(name = "4")
    ContactNumberText(4),

    @Json(name = "5")
    PlainText(5),

    @Json(name = "6")
    PlainTextOptional(6),

    @Json(name = "7")
    FaceToface(7),

    @Json(name = "8")
    Initial(8),

    @Json(name = "9")
    CheckBox(9),

    @Json(name = "10")
    F2FInitial(10),

    @Json(name = "11")
    AddressText(11),

    @Json(name = "12")
    CompanyNameText(12),

    @Json(name = "13")
    OptionalCurrencyText(13),

    @Json(name = "14")
    ReadOnlyText(14),

    @Json(name = "15")
    NumericFieldOpt(15),

    @Json(name = "16")
    NumericFieldMand(16),

    @Json(name = "17")
    EmailInputOptional(17),

    @Json(name = "18")
    EmailInput(18),

    @Json(name = "19")
    _19(19);


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value.toString()
    }
}

