/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * Portfolio information.
 * @param createPortfolioField Create portfolio.
 * @param linkToPortfolioField Portfolio link.
 * @param portfolioIDField Portfolio ID.
 * @param portfolioNameField Portfolio name.
 */

data class FullWorkflowRequestPortfolioInformationField (
    /* Create portfolio. */
    @Json(name = "CreatePortfolioField")
    val createPortfolioField: kotlin.Boolean,
    /* Portfolio link. */
    @Json(name = "LinkToPortfolioField")
    val linkToPortfolioField: kotlin.Boolean,
    /* Portfolio ID. */
    @Json(name = "PortfolioIDField")
    val portfolioIDField: java.math.BigDecimal,
    /* Portfolio name. */
    @Json(name = "PortfolioNameField")
    val portfolioNameField: kotlin.String
)

