/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.AutoRemind
import SigniFlow.Connect.models.DocExtension
import SigniFlow.Connect.models.FullWorkflowRequestPortfolioInformationField
import SigniFlow.Connect.models.FullWorkflowRequestWorkflowUsersListField
import SigniFlow.Connect.models.TokenField

import com.squareup.moshi.Json

/**
 * #### Request a fullworkflow of a document.
 * @param additionalDataField Additional data.
 * @param autoRemindField 
 * @param customMessageField Custom message.
 * @param docField Document field.
 * @param docNameField Document name.
 * @param dueDateField Document due date.
 * @param extensionField 
 * @param flattenDocumentField Flatten document.
 * @param keepContentSecurityField Keep content security.
 * @param keepCustomPropertiesField Keep custom properties.
 * @param keepXMPMetadataField Keep XMP meta data.
 * @param portfolioInformationField 
 * @param priorityField Document priority.
 * @param slAField SLA
 * @param sendFirstEmailField Confirm first user email notification will or will not be sent.
 * @param sendWorkflowEmailsField Confirm that workflow emails will or will not be sent.
 * @param tokenField 
 * @param workflowUsersListField List of users in the workflow.
 */

data class FullWorkflowRequest (
    /* Additional data. */
    @Json(name = "AdditionalDataField")
    val additionalDataField: kotlin.String,
    @Json(name = "AutoRemindField")
    val autoRemindField: AutoRemind,
    /* Custom message. */
    @Json(name = "CustomMessageField")
    val customMessageField: kotlin.String,
    /* Document field. */
    @Json(name = "DocField")
    val docField: kotlin.String,
    /* Document name. */
    @Json(name = "DocNameField")
    val docNameField: kotlin.String,
    /* Document due date. */
    @Json(name = "DueDateField")
    val dueDateField: kotlin.String,
    @Json(name = "ExtensionField")
    val extensionField: DocExtension,
    /* Flatten document. */
    @Json(name = "FlattenDocumentField")
    val flattenDocumentField: kotlin.Boolean,
    /* Keep content security. */
    @Json(name = "KeepContentSecurityField")
    val keepContentSecurityField: kotlin.Boolean,
    /* Keep custom properties. */
    @Json(name = "KeepCustomPropertiesField")
    val keepCustomPropertiesField: kotlin.Boolean,
    /* Keep XMP meta data. */
    @Json(name = "KeepXMPMetadataField")
    val keepXMPMetadataField: kotlin.Boolean,
    @Json(name = "PortfolioInformationField")
    val portfolioInformationField: FullWorkflowRequestPortfolioInformationField,
    /* Document priority. */
    @Json(name = "PriorityField")
    val priorityField: java.math.BigDecimal,
    /* SLA */
    @Json(name = "SLAField")
    val slAField: java.math.BigDecimal,
    /* Confirm first user email notification will or will not be sent. */
    @Json(name = "SendFirstEmailField")
    val sendFirstEmailField: kotlin.Boolean,
    /* Confirm that workflow emails will or will not be sent. */
    @Json(name = "SendWorkflowEmailsField")
    val sendWorkflowEmailsField: kotlin.Boolean,
    @Json(name = "TokenField")
    val tokenField: TokenField,
    /* List of users in the workflow. */
    @Json(name = "WorkflowUsersListField")
    val workflowUsersListField: kotlin.collections.List<FullWorkflowRequestWorkflowUsersListField>
)

