/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.FullWorkflowRequestGroupStepFieldGroupMembersField

import com.squareup.moshi.Json

/**
 * Steps of the group signers in the workflow.
 * @param groupMembersField The list of users in a group in the workflow.
 * @param groupNameField Group name.
 * @param requiredNumberOfSignaturesField Required number of signatures in the group.
 */

data class FullWorkflowRequestGroupStepField (
    /* The list of users in a group in the workflow. */
    @Json(name = "GroupMembersField")
    val groupMembersField: kotlin.collections.List<FullWorkflowRequestGroupStepFieldGroupMembersField>,
    /* Group name. */
    @Json(name = "GroupNameField")
    val groupNameField: kotlin.String,
    /* Required number of signatures in the group. */
    @Json(name = "RequiredNumberOfSignaturesField")
    val requiredNumberOfSignaturesField: java.math.BigDecimal
)

