/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * 
 * @param fieldTypeField Field type.
 * @param fontFamilyField The font family of the fields text.
 * @param fontSizeField The font size of the fields text.
 * @param groupUserNumberField The users in the group's user number.
 * @param heightField Field height.
 * @param isInvisibleField Is the field visible.
 * @param pageNumberField Field page number.
 * @param tagNameField Field tag name.
 * @param valueField Field value.
 * @param widthField Field width.
 * @param xcoordinateField The fields x-coordinates.
 * @param xoffsetField The fields x-coordinates offset.
 * @param ycoordinateField The fields y-coordinates.
 * @param yoffsetField The fields y-coordinates offset.
 */

data class FullWorkflowRequestWorkflowUserFieldsField (
    /* Field type. */
    @Json(name = "FieldTypeField")
    val fieldTypeField: java.math.BigDecimal,
    /* The font family of the fields text. */
    @Json(name = "FontFamilyField")
    val fontFamilyField: kotlin.String,
    /* The font size of the fields text. */
    @Json(name = "FontSizeField")
    val fontSizeField: java.math.BigDecimal,
    /* The users in the group's user number. */
    @Json(name = "GroupUserNumberField")
    val groupUserNumberField: java.math.BigDecimal,
    /* Field height. */
    @Json(name = "HeightField")
    val heightField: kotlin.String,
    /* Is the field visible. */
    @Json(name = "IsInvisibleField")
    val isInvisibleField: kotlin.Boolean,
    /* Field page number. */
    @Json(name = "PageNumberField")
    val pageNumberField: java.math.BigDecimal,
    /* Field tag name. */
    @Json(name = "TagNameField")
    val tagNameField: kotlin.String,
    /* Field value. */
    @Json(name = "ValueField")
    val valueField: kotlin.String,
    /* Field width. */
    @Json(name = "WidthField")
    val widthField: kotlin.String,
    /* The fields x-coordinates. */
    @Json(name = "XCoordinateField")
    val xcoordinateField: kotlin.String,
    /* The fields x-coordinates offset. */
    @Json(name = "XOffsetField")
    val xoffsetField: java.math.BigDecimal,
    /* The fields y-coordinates. */
    @Json(name = "YCoordinateField")
    val ycoordinateField: kotlin.String,
    /* The fields y-coordinates offset. */
    @Json(name = "YOffsetField")
    val yoffsetField: java.math.BigDecimal
)

