/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * 
 * @param languageCodeField 
 * @param userEmailField 
 * @param userFullNameField 
 * @param userMobileNumberField 
 */

data class FullWorkflowRequestGroupStepFieldGroupMembersField (
    @Json(name = "LanguageCodeField")
    val languageCodeField: kotlin.String,
    @Json(name = "UserEmailField")
    val userEmailField: kotlin.String,
    @Json(name = "UserFullNameField")
    val userFullNameField: kotlin.String,
    @Json(name = "UserMobileNumberField")
    val userMobileNumberField: kotlin.String
)

