/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * #### This is the response returned when requesting a document prepper url.
 * @param result Displays the result of the call.
 * @param URL Url
 */

data class GetDocumentPrepperLinkResponse (
    /* Displays the result of the call. */
    @Json(name = "Result")
    val result: kotlin.String,
    /* Url */
    @Json(name = "URL")
    val URL: kotlin.String
)

