/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * #### This is the response returned when a document url is requested.
 * @param result Displays the result of the call.
 * @param url URL
 */

data class GetDocLinkResponse (
    /* Displays the result of the call. */
    @Json(name = "Result")
    val result: kotlin.String,
    /* URL */
    @Json(name = "Url")
    val url: kotlin.String
)

