/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField

import com.squareup.moshi.Json

/**
 * #### The response returned when requesting the document tag field position.
 * @param documentTagFieldsPositionField 
 * @param resultField Displays the result of the call.
 */

data class GetDocumentTagFieldPositionResponse (
    @Json(name = "DocumentTagFieldsPositionField")
    val documentTagFieldsPositionField: kotlin.collections.List<GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField>,
    /* Displays the result of the call. */
    @Json(name = "ResultField")
    val resultField: kotlin.String
)

