/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * 
 * @param actionOrderField 
 * @param additionalField 
 * @param docIDField 
 * @param emailField The user's email.
 * @param eventDateField 
 * @param eventField 
 * @param eventStatusField 
 * @param locationField 
 * @param orderDateField 
 * @param pageField 
 * @param userFullNameField User's full name.
 */

data class GetDocumentAuditResponseActivityField (
    @Json(name = "ActionOrderField")
    val actionOrderField: kotlin.String,
    @Json(name = "AdditionalField")
    val additionalField: kotlin.String,
    @Json(name = "DocIDField")
    val docIDField: kotlin.String,
    /* The user's email. */
    @Json(name = "EmailField")
    val emailField: kotlin.String,
    @Json(name = "EventDateField")
    val eventDateField: kotlin.String,
    @Json(name = "EventField")
    val eventField: kotlin.String,
    @Json(name = "EventStatusField")
    val eventStatusField: kotlin.String,
    @Json(name = "LocationField")
    val locationField: kotlin.String,
    @Json(name = "OrderDateField")
    val orderDateField: kotlin.String,
    @Json(name = "PageField")
    val pageField: kotlin.String,
    /* User's full name. */
    @Json(name = "UserFullNameField")
    val userFullNameField: kotlin.String
)

