/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * 
 * @param pageNumberField The page number where the field is.
 * @param xcoordinateField The y coordinates of the field.
 * @param ycoordinateField The x coordinates of the field.
 */

data class GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField (
    /* The page number where the field is. */
    @Json(name = "PageNumberField")
    val pageNumberField: java.math.BigDecimal,
    /* The y coordinates of the field. */
    @Json(name = "XCoordinateField")
    val xcoordinateField: kotlin.String,
    /* The x coordinates of the field. */
    @Json(name = "YCoordinateField")
    val ycoordinateField: kotlin.String
)

