/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * 
 * @param nameField 
 * @param prepperTemplateIDField 
 * @param templateDescriptionField Template description.
 */

data class GetPrepperTemplateListResponseTemplateInformationValuesField (
    @Json(name = "NameField")
    val nameField: kotlin.String,
    @Json(name = "PrepperTemplateIDField")
    val prepperTemplateIDField: java.math.BigDecimal,
    /* Template description. */
    @Json(name = "TemplateDescriptionField")
    val templateDescriptionField: kotlin.String
)

