/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * 
 * @param colorField 
 * @param docFieldIDField 
 * @param docIDField 
 * @param fieldTypeField 
 * @param heightField Field height.
 * @param pageNumberField 
 * @param userFullNameField The user's full name.
 * @param userIDField The user's ID.
 * @param valueField 
 * @param widthField Field width.
 * @param xcoordinateField The x coordinates of the fields.
 * @param ycoordinateField The y coordinates of the fields
 */

data class GetPrepperTemplateResponsePrepperTemplateValuesField (
    @Json(name = "ColorField")
    val colorField: kotlin.String,
    @Json(name = "DocFieldIDField")
    val docFieldIDField: kotlin.String,
    @Json(name = "DocIDField")
    val docIDField: java.math.BigDecimal,
    @Json(name = "FieldTypeField")
    val fieldTypeField: kotlin.String,
    /* Field height. */
    @Json(name = "HeightField")
    val heightField: java.math.BigDecimal,
    @Json(name = "PageNumberField")
    val pageNumberField: java.math.BigDecimal,
    /* The user's full name. */
    @Json(name = "UserFullNameField")
    val userFullNameField: kotlin.String,
    /* The user's ID. */
    @Json(name = "UserIDField")
    val userIDField: java.math.BigDecimal,
    @Json(name = "ValueField")
    val valueField: kotlin.String,
    /* Field width. */
    @Json(name = "WidthField")
    val widthField: java.math.BigDecimal,
    /* The x coordinates of the fields. */
    @Json(name = "XCoordinateField")
    val xcoordinateField: java.math.BigDecimal,
    /* The y coordinates of the fields */
    @Json(name = "YCoordinateField")
    val ycoordinateField: java.math.BigDecimal
)

