/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * #### The request sent when a user Logs in.
 * @param userNameField Email address of the user generating a Token
 * @param passwordField SigniFlow user password
 */

data class LoginRequest (
    /* Email address of the user generating a Token */
    @Json(name = "UserNameField")
    val userNameField: kotlin.String,
    /* SigniFlow user password */
    @Json(name = "PasswordField")
    val passwordField: kotlin.String
)

