/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.MultipleSignersSigningCeremonyRequestSignerListField

import com.squareup.moshi.Json

/**
 * #### This is the request sent when there are multiple signers on a document.
 * @param docField 
 * @param docNameField 
 * @param loginPasswordField User's password.
 * @param loginUserNameField User's username.
 * @param signerListField 
 */

data class MultipleSignersSigningCeremonyRequest (
    @Json(name = "DocField")
    val docField: kotlin.String,
    @Json(name = "DocNameField")
    val docNameField: kotlin.String,
    /* User's password. */
    @Json(name = "LoginPasswordField")
    val loginPasswordField: kotlin.String,
    /* User's username. */
    @Json(name = "LoginUserNameField")
    val loginUserNameField: kotlin.String,
    @Json(name = "SignerListField")
    val signerListField: kotlin.collections.List<MultipleSignersSigningCeremonyRequestSignerListField>
)

