/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models

import SigniFlow.Connect.models.TokenField

import com.squareup.moshi.Json

/**
 * #### The request sent when a user wants to share a portfolio with someone.
 * @param accessLevelField 
 * @param portfolioIDField 
 * @param shareOptionField 
 * @param tokenField 
 * @param uniqueIDField 
 */

data class SharePortfolioRequest (
    @Json(name = "AccessLevelField")
    val accessLevelField: java.math.BigDecimal,
    @Json(name = "PortfolioIDField")
    val portfolioIDField: kotlin.String,
    @Json(name = "ShareOptionField")
    val shareOptionField: java.math.BigDecimal,
    @Json(name = "TokenField")
    val tokenField: TokenField,
    @Json(name = "UniqueIDField")
    val uniqueIDField: kotlin.String
)

