/**
* SigniFlow OpenAPI Spec v1
* ## SigniFlow API used to automate esignature workflow creation and management. 
*
* The version of the OpenAPI document: 1.0
* Contact: support@signiflow.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package SigniFlow.Connect.models


import com.squareup.moshi.Json

/**
 * #### The request sent to start the signing process of a document.
 * @param checkboxFieldsListField 
 * @param docField 
 * @param docNameField 
 * @param initialFieldsListField 
 * @param loginPasswordField 
 * @param loginUserNameField 
 * @param signatureHField 
 * @param signatureImageField 
 * @param signatureImageIncludeBorderField 
 * @param signatureImageIncludeReasonField 
 * @param signatureImageIncludeSignedByField 
 * @param signatureImageIncludeSignedDateField 
 * @param signatureImageTypeField 
 * @param signaturePageField 
 * @param signatureWField 
 * @param signatureXField 
 * @param signatureYField 
 * @param signerEmailField 
 * @param signerFullNameField 
 * @param signerIdentificationNumberField 
 * @param signerLocationField 
 * @param signerMobileNumberField 
 * @param signerReasonField 
 * @param signerTrustOriginField 
 * @param signerTrustReferenceField 
 * @param textFieldsListField 
 */

data class SigningCeremonyV2Request (
    @Json(name = "CheckboxFieldsListField")
    val checkboxFieldsListField: kotlin.collections.List<kotlin.Any>,
    @Json(name = "DocField")
    val docField: kotlin.String,
    @Json(name = "DocNameField")
    val docNameField: kotlin.String,
    @Json(name = "InitialFieldsListField")
    val initialFieldsListField: kotlin.collections.List<kotlin.Any>,
    @Json(name = "LoginPasswordField")
    val loginPasswordField: kotlin.String,
    @Json(name = "LoginUserNameField")
    val loginUserNameField: kotlin.String,
    @Json(name = "SignatureHField")
    val signatureHField: java.math.BigDecimal,
    @Json(name = "SignatureImageField")
    val signatureImageField: kotlin.String,
    @Json(name = "SignatureImageIncludeBorderField")
    val signatureImageIncludeBorderField: kotlin.Boolean,
    @Json(name = "SignatureImageIncludeReasonField")
    val signatureImageIncludeReasonField: kotlin.Boolean,
    @Json(name = "SignatureImageIncludeSignedByField")
    val signatureImageIncludeSignedByField: kotlin.Boolean,
    @Json(name = "SignatureImageIncludeSignedDateField")
    val signatureImageIncludeSignedDateField: kotlin.Boolean,
    @Json(name = "SignatureImageTypeField")
    val signatureImageTypeField: java.math.BigDecimal,
    @Json(name = "SignaturePageField")
    val signaturePageField: java.math.BigDecimal,
    @Json(name = "SignatureWField")
    val signatureWField: java.math.BigDecimal,
    @Json(name = "SignatureXField")
    val signatureXField: java.math.BigDecimal,
    @Json(name = "SignatureYField")
    val signatureYField: java.math.BigDecimal,
    @Json(name = "SignerEmailField")
    val signerEmailField: kotlin.String,
    @Json(name = "SignerFullNameField")
    val signerFullNameField: kotlin.String,
    @Json(name = "SignerIdentificationNumberField")
    val signerIdentificationNumberField: kotlin.String,
    @Json(name = "SignerLocationField")
    val signerLocationField: kotlin.String,
    @Json(name = "SignerMobileNumberField")
    val signerMobileNumberField: kotlin.String,
    @Json(name = "SignerReasonField")
    val signerReasonField: kotlin.String,
    @Json(name = "SignerTrustOriginField")
    val signerTrustOriginField: kotlin.String,
    @Json(name = "SignerTrustReferenceField")
    val signerTrustReferenceField: kotlin.String,
    @Json(name = "TextFieldsListField")
    val textFieldsListField: kotlin.collections.List<kotlin.Any>
)

